import type { Equipment, MovementType } from '../types';

/**
 * Seed definitions. Muscle groups and system exercises use stable string
 * ids (slugs) so seeding is idempotent and exercise → muscle references
 * stay valid across reloads.
 */

export const MUSCLE_GROUP_SEED: { id: string; name: string }[] = [
  { id: 'mg-chest', name: 'Chest' },
  { id: 'mg-back', name: 'Back' },
  { id: 'mg-shoulders', name: 'Shoulders' },
  { id: 'mg-biceps', name: 'Biceps' },
  { id: 'mg-triceps', name: 'Triceps' },
  { id: 'mg-forearms', name: 'Forearms' },
  { id: 'mg-quads', name: 'Quads' },
  { id: 'mg-hamstrings', name: 'Hamstrings' },
  { id: 'mg-glutes', name: 'Glutes' },
  { id: 'mg-calves', name: 'Calves' },
  { id: 'mg-abs', name: 'Abs' },
];

export interface ExerciseSeed {
  id: string;
  name: string;
  primary: string; // muscle group id
  secondary?: string[];
  equipment: Equipment;
  movement_type: MovementType;
  is_compound: boolean;
}

export const EXERCISE_SEED: ExerciseSeed[] = [
  // Chest
  {
    id: 'ex-barbell-bench-press',
    name: 'Barbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-shoulders', 'mg-triceps'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primary: 'mg-chest',
    secondary: ['mg-shoulders', 'mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-cable-fly',
    name: 'Cable Fly',
    primary: 'mg-chest',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-pec-deck',
    name: 'Pec Deck Machine',
    primary: 'mg-chest',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-push-up',
    name: 'Push-Up',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'bodyweight',
    movement_type: 'push',
    is_compound: true,
  },
  // Back
  {
    id: 'ex-deadlift',
    name: 'Deadlift',
    primary: 'mg-back',
    secondary: ['mg-hamstrings', 'mg-glutes', 'mg-forearms'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-pull-up',
    name: 'Pull-Up',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'bodyweight',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-chin-up',
    name: 'Chin-Up',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'bodyweight',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-t-bar-row',
    name: 'T-Bar Row',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-face-pull',
    name: 'Face Pull',
    primary: 'mg-shoulders',
    secondary: ['mg-back'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: false,
  },
  // Shoulders
  {
    id: 'ex-overhead-press',
    name: 'Overhead Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Lateral Raise',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Rear Delt Fly',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-arnold-press',
    name: 'Arnold Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-front-raise',
    name: 'Front Raise',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Biceps
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'barbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Dumbbell Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammer Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-preacher-curl',
    name: 'Preacher Curl',
    primary: 'mg-biceps',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-cable-curl',
    name: 'Cable Curl',
    primary: 'mg-biceps',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Triceps
  {
    id: 'ex-close-grip-bench',
    name: 'Close-Grip Bench Press',
    primary: 'mg-triceps',
    secondary: ['mg-chest', 'mg-shoulders'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-tricep-pushdown',
    name: 'Tricep Pushdown',
    primary: 'mg-triceps',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    primary: 'mg-triceps',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-skull-crusher',
    name: 'Skull Crusher',
    primary: 'mg-triceps',
    equipment: 'barbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-tricep-dip',
    name: 'Tricep Dip',
    primary: 'mg-triceps',
    secondary: ['mg-chest', 'mg-shoulders'],
    equipment: 'bodyweight',
    movement_type: 'push',
    is_compound: true,
  },
  // Forearms
  {
    id: 'ex-wrist-curl',
    name: 'Wrist Curl',
    primary: 'mg-forearms',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-farmers-carry',
    name: "Farmer's Carry",
    primary: 'mg-forearms',
    secondary: ['mg-glutes'],
    equipment: 'dumbbell',
    movement_type: 'carry',
    is_compound: true,
  },
  // Quads
  {
    id: 'ex-back-squat',
    name: 'Barbell Back Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'barbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-front-squat',
    name: 'Front Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes'],
    equipment: 'barbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-leg-press',
    name: 'Leg Press',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'machine',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension',
    primary: 'mg-quads',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-lunge',
    name: 'Walking Lunge',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  // Hamstrings
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift',
    primary: 'mg-hamstrings',
    secondary: ['mg-glutes', 'mg-back'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-lying-leg-curl',
    name: 'Lying Leg Curl',
    primary: 'mg-hamstrings',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-seated-leg-curl',
    name: 'Seated Leg Curl',
    primary: 'mg-hamstrings',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-good-morning',
    name: 'Good Morning',
    primary: 'mg-hamstrings',
    secondary: ['mg-glutes', 'mg-back'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  // Glutes
  {
    id: 'ex-hip-thrust',
    name: 'Barbell Hip Thrust',
    primary: 'mg-glutes',
    secondary: ['mg-hamstrings'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-glute-bridge',
    name: 'Glute Bridge',
    primary: 'mg-glutes',
    secondary: ['mg-hamstrings'],
    equipment: 'bodyweight',
    movement_type: 'hinge',
    is_compound: false,
  },
  {
    id: 'ex-cable-kickback',
    name: 'Cable Glute Kickback',
    primary: 'mg-glutes',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Calves
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    primary: 'mg-calves',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Seated Calf Raise',
    primary: 'mg-calves',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Abs
  {
    id: 'ex-plank',
    name: 'Plank',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-cable-crunch',
    name: 'Cable Crunch',
    primary: 'mg-abs',
    equipment: 'cable',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-ab-wheel',
    name: 'Ab Wheel Rollout',
    primary: 'mg-abs',
    equipment: 'other',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-russian-twist',
    name: 'Russian Twist',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
];
