import type { DayOfWeek, Equipment, MovementType } from '../types';

/**
 * Seed definitions. Muscle groups and system exercises use stable string
 * ids (slugs) so seeding is idempotent and exercise → muscle references
 * stay valid across reloads.
 */

export const MUSCLE_GROUP_SEED: { id: string; name: string }[] = [
  { id: 'mg-chest', name: 'Chest' },
  { id: 'mg-back', name: 'Back' },
  { id: 'mg-shoulders', name: 'Shoulders' },
  { id: 'mg-biceps', name: 'Biceps' },
  { id: 'mg-triceps', name: 'Triceps' },
  { id: 'mg-forearms', name: 'Forearms' },
  { id: 'mg-quads', name: 'Quads' },
  { id: 'mg-hamstrings', name: 'Hamstrings' },
  { id: 'mg-glutes', name: 'Glutes' },
  { id: 'mg-calves', name: 'Calves' },
  { id: 'mg-abs', name: 'Abs' },
];

export interface ExerciseSeed {
  id: string;
  name: string;
  primary: string; // muscle group id
  secondary?: string[];
  equipment: Equipment;
  movement_type: MovementType;
  is_compound: boolean;
}

export const EXERCISE_SEED: ExerciseSeed[] = [
  // Chest
  {
    id: 'ex-barbell-bench-press',
    name: 'Barbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-shoulders', 'mg-triceps'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primary: 'mg-chest',
    secondary: ['mg-shoulders', 'mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-cable-fly',
    name: 'Cable Fly',
    primary: 'mg-chest',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-pec-deck',
    name: 'Pec Deck Machine',
    primary: 'mg-chest',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-push-up',
    name: 'Push-Up',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'bodyweight',
    movement_type: 'push',
    is_compound: true,
  },
  // Back
  {
    id: 'ex-deadlift',
    name: 'Deadlift',
    primary: 'mg-back',
    secondary: ['mg-hamstrings', 'mg-glutes', 'mg-forearms'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-pull-up',
    name: 'Pull-Up',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'bodyweight',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-chin-up',
    name: 'Chin-Up',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'bodyweight',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    primary: 'mg-back',
    secondary: ['mg-biceps', 'mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-t-bar-row',
    name: 'T-Bar Row',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-face-pull',
    name: 'Face Pull',
    primary: 'mg-shoulders',
    secondary: ['mg-back'],
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: false,
  },
  // Shoulders
  {
    id: 'ex-overhead-press',
    name: 'Overhead Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Lateral Raise',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Rear Delt Fly',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-arnold-press',
    name: 'Arnold Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'dumbbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-front-raise',
    name: 'Front Raise',
    primary: 'mg-shoulders',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Biceps
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'barbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Dumbbell Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammer Curl',
    primary: 'mg-biceps',
    secondary: ['mg-forearms'],
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-preacher-curl',
    name: 'Preacher Curl',
    primary: 'mg-biceps',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-cable-curl',
    name: 'Cable Curl',
    primary: 'mg-biceps',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Triceps
  {
    id: 'ex-close-grip-bench',
    name: 'Close-Grip Bench Press',
    primary: 'mg-triceps',
    secondary: ['mg-chest', 'mg-shoulders'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-tricep-pushdown',
    name: 'Tricep Pushdown',
    primary: 'mg-triceps',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    primary: 'mg-triceps',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-skull-crusher',
    name: 'Skull Crusher',
    primary: 'mg-triceps',
    equipment: 'barbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-tricep-dip',
    name: 'Tricep Dip',
    primary: 'mg-triceps',
    secondary: ['mg-chest', 'mg-shoulders'],
    equipment: 'bodyweight',
    movement_type: 'push',
    is_compound: true,
  },
  // Forearms
  {
    id: 'ex-wrist-curl',
    name: 'Wrist Curl',
    primary: 'mg-forearms',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-farmers-carry',
    name: "Farmer's Carry",
    primary: 'mg-forearms',
    secondary: ['mg-glutes'],
    equipment: 'dumbbell',
    movement_type: 'carry',
    is_compound: true,
  },
  // Quads
  {
    id: 'ex-back-squat',
    name: 'Barbell Back Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'barbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-front-squat',
    name: 'Front Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes'],
    equipment: 'barbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-leg-press',
    name: 'Leg Press',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'machine',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension',
    primary: 'mg-quads',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-lunge',
    name: 'Walking Lunge',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  // Hamstrings
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift',
    primary: 'mg-hamstrings',
    secondary: ['mg-glutes', 'mg-back'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-lying-leg-curl',
    name: 'Lying Leg Curl',
    primary: 'mg-hamstrings',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-seated-leg-curl',
    name: 'Seated Leg Curl',
    primary: 'mg-hamstrings',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-good-morning',
    name: 'Good Morning',
    primary: 'mg-hamstrings',
    secondary: ['mg-glutes', 'mg-back'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  // Glutes
  {
    id: 'ex-hip-thrust',
    name: 'Barbell Hip Thrust',
    primary: 'mg-glutes',
    secondary: ['mg-hamstrings'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-glute-bridge',
    name: 'Glute Bridge',
    primary: 'mg-glutes',
    secondary: ['mg-hamstrings'],
    equipment: 'bodyweight',
    movement_type: 'hinge',
    is_compound: false,
  },
  {
    id: 'ex-cable-kickback',
    name: 'Cable Glute Kickback',
    primary: 'mg-glutes',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Calves
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    primary: 'mg-calves',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Seated Calf Raise',
    primary: 'mg-calves',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Abs
  {
    id: 'ex-plank',
    name: 'Plank',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-cable-crunch',
    name: 'Cable Crunch',
    primary: 'mg-abs',
    equipment: 'cable',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-ab-wheel',
    name: 'Ab Wheel Rollout',
    primary: 'mg-abs',
    equipment: 'other',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-russian-twist',
    name: 'Russian Twist',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  // --- Additional library ---------------------------------------------------
  // Chest
  {
    id: 'ex-decline-barbell-bench-press',
    name: 'Decline Barbell Bench Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps'],
    equipment: 'barbell',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-machine-chest-press',
    name: 'Machine Chest Press',
    primary: 'mg-chest',
    secondary: ['mg-triceps', 'mg-shoulders'],
    equipment: 'machine',
    movement_type: 'push',
    is_compound: true,
  },
  // Back
  {
    id: 'ex-barbell-shrug',
    name: 'Barbell Shrug',
    primary: 'mg-back',
    secondary: ['mg-forearms'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: false,
  },
  {
    id: 'ex-chest-supported-row',
    name: 'Chest-Supported Row',
    primary: 'mg-back',
    secondary: ['mg-biceps'],
    equipment: 'machine',
    movement_type: 'pull',
    is_compound: true,
  },
  {
    id: 'ex-straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    primary: 'mg-back',
    equipment: 'cable',
    movement_type: 'pull',
    is_compound: false,
  },
  {
    id: 'ex-rack-pull',
    name: 'Rack Pull',
    primary: 'mg-back',
    secondary: ['mg-glutes', 'mg-hamstrings', 'mg-forearms'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-dumbbell-pullover',
    name: 'Dumbbell Pullover',
    primary: 'mg-back',
    secondary: ['mg-chest'],
    equipment: 'dumbbell',
    movement_type: 'pull',
    is_compound: true,
  },
  // Shoulders
  {
    id: 'ex-machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primary: 'mg-shoulders',
    secondary: ['mg-triceps'],
    equipment: 'machine',
    movement_type: 'push',
    is_compound: true,
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primary: 'mg-shoulders',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-upright-row',
    name: 'Upright Row',
    primary: 'mg-shoulders',
    secondary: ['mg-back', 'mg-biceps'],
    equipment: 'barbell',
    movement_type: 'pull',
    is_compound: true,
  },
  // Biceps
  {
    id: 'ex-incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primary: 'mg-biceps',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-concentration-curl',
    name: 'Concentration Curl',
    primary: 'mg-biceps',
    equipment: 'dumbbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Triceps
  {
    id: 'ex-overhead-rope-extension',
    name: 'Overhead Rope Extension',
    primary: 'mg-triceps',
    equipment: 'cable',
    movement_type: 'isolation',
    is_compound: false,
  },
  {
    id: 'ex-bench-dip',
    name: 'Bench Dip',
    primary: 'mg-triceps',
    secondary: ['mg-chest', 'mg-shoulders'],
    equipment: 'bodyweight',
    movement_type: 'push',
    is_compound: false,
  },
  // Forearms
  {
    id: 'ex-reverse-curl',
    name: 'Reverse Curl',
    primary: 'mg-forearms',
    secondary: ['mg-biceps'],
    equipment: 'barbell',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Quads
  {
    id: 'ex-hack-squat',
    name: 'Hack Squat',
    primary: 'mg-quads',
    secondary: ['mg-glutes'],
    equipment: 'machine',
    movement_type: 'squat',
    is_compound: true,
  },
  {
    id: 'ex-step-up',
    name: 'Step-Up',
    primary: 'mg-quads',
    secondary: ['mg-glutes', 'mg-hamstrings'],
    equipment: 'dumbbell',
    movement_type: 'squat',
    is_compound: true,
  },
  // Hamstrings / glutes
  {
    id: 'ex-sumo-deadlift',
    name: 'Sumo Deadlift',
    primary: 'mg-hamstrings',
    secondary: ['mg-glutes', 'mg-quads', 'mg-back'],
    equipment: 'barbell',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-cable-pull-through',
    name: 'Cable Pull-Through',
    primary: 'mg-glutes',
    secondary: ['mg-hamstrings'],
    equipment: 'cable',
    movement_type: 'hinge',
    is_compound: true,
  },
  {
    id: 'ex-hip-abduction',
    name: 'Hip Abduction Machine',
    primary: 'mg-glutes',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Calves
  {
    id: 'ex-leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    primary: 'mg-calves',
    equipment: 'machine',
    movement_type: 'isolation',
    is_compound: false,
  },
  // Abs
  {
    id: 'ex-sit-up',
    name: 'Sit-Up',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-bicycle-crunch',
    name: 'Bicycle Crunch',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
  {
    id: 'ex-side-plank',
    name: 'Side Plank',
    primary: 'mg-abs',
    equipment: 'bodyweight',
    movement_type: 'core',
    is_compound: false,
  },
];

/** A starter routine template (seeded once on first launch). */
export interface RoutineSeed {
  id: string;
  name: string;
  notes?: string;
  day_of_week?: DayOfWeek;
  exercises: { exercise_id: string; sets: number; low: number; high: number }[];
}

export const ROUTINE_SEED: RoutineSeed[] = [
  {
    id: 'rt-push',
    name: 'Push Day',
    notes: 'Chest, shoulders & triceps',
    exercises: [
      { exercise_id: 'ex-barbell-bench-press', sets: 4, low: 6, high: 10 },
      { exercise_id: 'ex-incline-dumbbell-press', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-overhead-press', sets: 3, low: 6, high: 10 },
      { exercise_id: 'ex-lateral-raise', sets: 3, low: 12, high: 15 },
      { exercise_id: 'ex-tricep-pushdown', sets: 3, low: 10, high: 15 },
      { exercise_id: 'ex-overhead-tricep-extension', sets: 3, low: 10, high: 15 },
    ],
  },
  {
    id: 'rt-pull',
    name: 'Pull Day',
    notes: 'Back & biceps',
    exercises: [
      { exercise_id: 'ex-barbell-row', sets: 4, low: 6, high: 10 },
      { exercise_id: 'ex-lat-pulldown', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-seated-cable-row', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-face-pull', sets: 3, low: 12, high: 15 },
      { exercise_id: 'ex-barbell-curl', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-hammer-curl', sets: 3, low: 10, high: 15 },
    ],
  },
  {
    id: 'rt-legs',
    name: 'Leg Day',
    notes: 'Quads, hamstrings, glutes & calves',
    exercises: [
      { exercise_id: 'ex-back-squat', sets: 4, low: 5, high: 8 },
      { exercise_id: 'ex-romanian-deadlift', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-leg-press', sets: 3, low: 10, high: 15 },
      { exercise_id: 'ex-lying-leg-curl', sets: 3, low: 10, high: 15 },
      { exercise_id: 'ex-standing-calf-raise', sets: 4, low: 12, high: 20 },
    ],
  },
  {
    id: 'rt-upper',
    name: 'Upper Body',
    notes: 'Upper/lower split — upper day',
    exercises: [
      { exercise_id: 'ex-barbell-bench-press', sets: 4, low: 6, high: 10 },
      { exercise_id: 'ex-barbell-row', sets: 4, low: 6, high: 10 },
      { exercise_id: 'ex-overhead-press', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-lat-pulldown', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-dumbbell-curl', sets: 3, low: 10, high: 15 },
      { exercise_id: 'ex-tricep-pushdown', sets: 3, low: 10, high: 15 },
    ],
  },
  {
    id: 'rt-lower',
    name: 'Lower Body',
    notes: 'Upper/lower split — lower day',
    exercises: [
      { exercise_id: 'ex-back-squat', sets: 4, low: 5, high: 8 },
      { exercise_id: 'ex-romanian-deadlift', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-bulgarian-split-squat', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-leg-extension', sets: 3, low: 12, high: 15 },
      { exercise_id: 'ex-standing-calf-raise', sets: 4, low: 12, high: 20 },
    ],
  },
  {
    id: 'rt-full-body',
    name: 'Full Body',
    notes: 'A balanced whole-body session',
    exercises: [
      { exercise_id: 'ex-back-squat', sets: 3, low: 5, high: 8 },
      { exercise_id: 'ex-barbell-bench-press', sets: 3, low: 6, high: 10 },
      { exercise_id: 'ex-barbell-row', sets: 3, low: 6, high: 10 },
      { exercise_id: 'ex-overhead-press', sets: 3, low: 8, high: 12 },
      { exercise_id: 'ex-barbell-curl', sets: 3, low: 10, high: 15 },
    ],
  },
];
